In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as image
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import PIL
import os
from PIL import Image

In [3]:
f0 = []
for i in range(0,4132):
    photos = Image.open(r"C:\Users\dell\Desktop\Folders\Innomatics\Machine learning\mnist_data\0\img_{}.png".format(i))
    photos_gray_0 = photos.convert("L") #converted to gray scale
    photos_arr_0 = np.array(photos_gray_0) #matrix to numpy array
    f0.append(photos_arr_0.ravel()) #numpy array to df ( flatten)
print("gray image shape:",photos_gray_0)
print("photos_array_size",photos_arr_0.size)

SyntaxError: invalid syntax (Temp/ipykernel_16092/3907491545.py, line 3)

In [3]:
f1 = []
for i in range(0,4684):
    photos = Image.open(r"C:\Users\dell\Desktop\Folders\Innomatics\Machine learning\mnist_data\1\img_{}.png".format(i))
    photos_gray_0 = photos.convert("L")
    photos_arr_0 = np.array(photos_gray_0)
    f1.append(photos_arr_0.ravel())
print("gray image shape:",photos_gray_0)
print("photos_array_size",photos_arr_0.size)

gray image shape: <PIL.Image.Image image mode=L size=28x28 at 0x25F47943F70>
photos_array_size 784

In [4]:
f2 = []
for i in range(0,4177):
    photos = Image.open(r"C:\Users\dell\Desktop\Folders\Innomatics\Machine learning\mnist_data\2\img_{}.png".format(i))
    photos_gray_0 = photos.convert("L")
    photos_arr_0 = np.array(photos_gray_0)
    f2.append(photos_arr_0.ravel())
print("gray image shape:",photos_gray_0)
print("photos_array_size",photos_arr_0.size)

gray image shape: <PIL.Image.Image image mode=L size=28x28 at 0x25F4CB407F0>
photos_array_size 784

In [5]:
f3 = []
for i in range(0,4351):
    photos = Image.open(r"C:\Users\dell\Desktop\Folders\Innomatics\Machine learning\mnist_data\3\img_{}.png".format(i))
    photos_gray_0 = photos.convert("L")
    photos_arr_0 = np.array(photos_gray_0)
    f3.append(photos_arr_0.ravel())
print("gray image shape:",photos_gray_0)
print("photos_array_size",photos_arr_0.size)

gray image shape: <PIL.Image.Image image mode=L size=28x28 at 0x25F4CB40C70>
photos_array_size 784

In [6]:
f4 = []
for i in range(0,4072):
    photos = Image.open(r"C:\Users\dell\Desktop\Folders\Innomatics\Machine learning\mnist_data\4\img_{}.png".format(i))
    photos_gray_0 = photos.convert("L")
    photos_arr_0 = np.array(photos_gray_0)
    f4.append(photos_arr_0.ravel())
print("gray image shape:",photos_gray_0)
print("photos_array_size",photos_arr_0.size)

gray image shape: <PIL.Image.Image image mode=L size=28x28 at 0x25F4CB40AC0>
photos_array_size 784

In [7]:
f5 = []
for i in range(0,3795):
    photos = Image.open(r"C:\Users\dell\Desktop\Folders\Innomatics\Machine learning\mnist_data\5\img_{}.png".format(i))
    photos_gray_0 = photos.convert("L")
    photos_arr_0 = np.array(photos_gray_0)
    f5.append(photos_arr_0.ravel())
print("gray image shape:",photos_gray_0)
print("photos_array_size",photos_arr_0.size)

gray image shape: <PIL.Image.Image image mode=L size=28x28 at 0x25F4CB40FD0>
photos_array_size 784

In [8]:
f6 = []
for i in range(0,4137):
    photos = Image.open(r"C:\Users\dell\Desktop\Folders\Innomatics\Machine learning\mnist_data\6\img_{}.png".format(i))
    photos_gray_0 = photos.convert("L")
    photos_arr_0 = np.array(photos_gray_0)
    f6.append(photos_arr_0.ravel())
print("gray image shape:",photos_gray_0)
print("photos_array_size",photos_arr_0.size)

gray image shape: <PIL.Image.Image image mode=L size=28x28 at 0x25F4DE232B0>
photos_array_size 784

In [9]:
f7 = []
for i in range(0,4401):
    photos = Image.open(r"C:\Users\dell\Desktop\Folders\Innomatics\Machine learning\mnist_data\7\img_{}.png".format(i))
    photos_gray_0 = photos.convert("L")
    photos_arr_0 = np.array(photos_gray_0)
    f7.append(photos_arr_0.ravel())
print("gray image shape:",photos_gray_0)
print("photos_array_size",photos_arr_0.size)

gray image shape: <PIL.Image.Image image mode=L size=28x28 at 0x25F4CB40F70>
photos_array_size 784

In [10]:
f8 = []
for i in range(0,4063):
    photos = Image.open(r"C:\Users\dell\Desktop\Folders\Innomatics\Machine learning\mnist_data\8\img_{}.png".format(i))
    photos_gray_0 = photos.convert("L")
    photos_arr_0 = np.array(photos_gray_0)
    f8.append(photos_arr_0.ravel())
print("gray image shape:",photos_gray_0)
print("photos_array_size",photos_arr_0.size)

gray image shape: <PIL.Image.Image image mode=L size=28x28 at 0x25F47980AC0>
photos_array_size 784

In [11]:
f9 = []
for i in range(0,4188):
    photos = Image.open(r"C:\Users\dell\Desktop\Folders\Innomatics\Machine learning\mnist_data\9\img_{}.png".format(i))
    photos_gray_0 = photos.convert("L") 
    photos_arr_0 = np.array(photos_gray_0)
    f9.append(photos_arr_0.ravel())
print("gray image shape:",photos_gray_0)
print("photos_array_size",photos_arr_0.size)

gray image shape: <PIL.Image.Image image mode=L size=28x28 at 0x25F4CB401F0>
photos_array_size 784

In [12]:
df0 = pd.DataFrame(f0)
df1 = pd.DataFrame(f1)
df2 = pd.DataFrame(f2)
df3 = pd.DataFrame(f3)
df4 = pd.DataFrame(f4)
df5 = pd.DataFrame(f5)
df6 = pd.DataFrame(f6)
df7 = pd.DataFrame(f7)
df8 = pd.DataFrame(f8)
df9 = pd.DataFrame(f9)

In [13]:
df0["label"]=0
df1["label"]=1
df2["label"]=2
df3["label"]=3
df4["label"]=4
df5["label"]=5
df6["label"]=6
df7["label"]=7
df8["label"]=8
df9["label"]=9

In [14]:
data = pd.concat([df0, df1, df2, df3, df4, df5, df6, df7, df8, df9], axis=0)

In [15]:
data

,0,1,2,3,4,5,6,7,8,9,...,775,776,777,778,779,780,781,782,783,label
0,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,0
1,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,0
2,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,0
3,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,0
4,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4183,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,9
4184,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,9
4185,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,9
4186,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,9
4187,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,9

In [16]:
data.to_csv('df.csv', index=False)

In [2]:
df = pd.read_csv (r'C:\Users\dell\Data Science\Machine learning\Projects\Digital hand written classifier\df.csv')
df

,0,1,2,3,4,5,6,7,8,9,...,775,776,777,778,779,780,781,782,783,label
0,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,0
1,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,0
2,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,0
3,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,0
4,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41995,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,9
41996,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,9
41997,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,9
41998,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,9
41999,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,9